baseURL: "https://guangchen811.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Hao Chen
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-R12XP6LSRD

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Hao Chen
  # author: ["Me", "You"] # multiple authors
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: true
  images: ["papermod-cover.png"]
  math: true
  profileMode:
    enabled: true
    title: "Welcome to my blog! \U0001F44B"
    subtitle: Hi there, this is Hao Chen, a Master student at Beijing Normal University. I am currently doing research on the field of Knowledge Graph and Language Model. I am documenting my acquired knowledge here. It can't be better if they are useful for you! For more information about me, please visit my LinkedIn profile.
    imageUrl: "/images/avatar.jpg"
    imageTitle: avatar
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archive
        url: archives
        weight: 5
      - name: Search
        url: search/
        weight: 4
      - name: Tags
        url: tags/
        weight: 3
      - name: Categories
        url: categories/
        weight: 2
  ShowAllPagesInArchive: true

  socialIcons:
    - name: github
      url: "https://github.com/guangchen811/guangchen811.github.io"
    - name: RsS
      url: "index.xml"
    - name: linkedin
      url: "https://www.linkedin.com/in/hao-chen-69b175203/"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=8_8CyzcAAAAJ&hl=en"

  assets:
    favicon: "/images/favicon.png"
    favicon16x16: "/images/favicon.png"
    favicon32x32: "/images/favicon.png"

taxonomies:
  category: categories
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      footnote: true
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true

languages:
    en:
        languageName: "en"
        weight: 1
        menu:
            main:
                - name: CV
                  url: cv/
                  weight: 1
                - name: Search
                  url: search/
                  weight: 4
                - name: Archive
                  url: archives/
                  weight: 5
                - name: Recommended Blogs
                  pageRef: /Recommended
                  weight: 6
                - name: DescKGC
                  url: https://guangchen811.github.io/DescKGC/
                  weight: 7

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
