baseURL: "https://guangchen811.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Hao Chen
paginate: 5
theme: PaperMod



enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-R12XP6LSRD

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        params:
            Title: "Welcome to my blog! \U0001F44B"
            Content: Hi there, this is Hao.  I am currently documenting my acquired knowledge. It can't be better if my blogs are useful for you!
        languageName: "en"
        weight: 1
        menu:
            main:
                - name: CV
                  url: cv
                  weight: 1
                - name: Search
                  url: search/
                  weight: 4
                - name: Archive
                  url: archives/
                  weight: 5
                - name: Recommended Blogs
                  url: /Recommended/
                  weight: 6
                - name: DescKGC
                  url: https://guangchen811.github.io/DescKGC/
                  weight: 7

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Hao Chen
    # author: ["Me", "You"] # multiple authors
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: Welcome to my blog!
        subtitle: Hi there, this is Hao. I am currently documenting my acquired knowledge. It can't be better if they are useful for you! For more information about me, please visit my LinkedIn profile.
        imageUrl: "/images/avatar.jpg"
        imageTitle: avatar
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archive
              url: archives
              weight: 5
            - name: Search
              url: search/
              weight: 4
            - name: Tags
              url: tags/
              weight: 3
            - name: Categories
              url: categories/
              weight: 2
    ShowAllPagesInArchive: true
    # homeInfoParams:
    #     Title: "PaperMod"
    #     Content: >
    #         Welcome to demo of hugo's theme PaperMod.

    #         - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

    #         - Do give a 🌟 on Github !

    #         - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    socialIcons:
        - name: github
          url: "https://github.com/guangchen811/guangchen811.github.io"
        - name: RsS
          url: "index.xml"
        - name: linkedin
          url : "https://www.linkedin.com/in/hao-chen-69b175203/"
        - name: googlescholar
          url: "https://scholar.google.com/citations?user=8_8CyzcAAAAJ&hl=en"
        # - name: KoFi
        #   url: "https://ko-fi.com/adityatelange"
    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        favicon: "/images/favicon.png"
        favicon16x16: "/images/favicon.png"
        favicon32x32: "/images/favicon.png"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    # series: series

markup:
    goldmark:
        renderer:
            unsafe: true
    # highlight:
    #     # anchorLineNos: true
    #     codeFences: true
    #     guessSyntax: true
    #     lineNos: true
    #     # noClasses: false
    #     style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
